-- ============================================================================
-- NEW_FTFP View Creation
-- Created: 2026-04-04
-- ============================================================================
--
-- Views updated to reference NEW_FTFP.DATA tables.
-- ROUTE_GEOMETRY_DETAILED kept for backward compat (uses FREIGHT_EDGES).
-- In production, Valhalla generates route geometry dynamically.
-- ============================================================================

USE SCHEMA NEW_FTFP.DATA;

-- ===========================================================================
-- View 1: TELEMETRY_5MIN_AGG
-- ===========================================================================

CREATE OR REPLACE VIEW TELEMETRY_5MIN_AGG AS
SELECT
    TIME_SLICE(TIMESTAMP, 5, 'MINUTE', 'END') AS BUCKET_TIME,
    ENTITY_ID,
    AVG(ENGINE_TEMP) AS AVG_ENGINE_TEMP,
    AVG(TRANS_OIL_PRESSURE) AS AVG_TRANS_OIL_PRESSURE,
    AVG(BATTERY_VOLTAGE) AS AVG_BATTERY_VOLTAGE,
    COUNT(*) AS POINT_COUNT,
    MAX(TIMESTAMP) AS LATEST_TIMESTAMP
FROM NEW_FTFP.DATA.TELEMETRY
GROUP BY TIME_SLICE(TIMESTAMP, 5, 'MINUTE', 'END'), ENTITY_ID;

-- ===========================================================================
-- View 2: FEATURE_ENGINEERING_VIEW_TEMPORAL
-- ===========================================================================

CREATE OR REPLACE VIEW FEATURE_ENGINEERING_VIEW_TEMPORAL AS
WITH time_windows AS (
    SELECT
        ENTITY_ID, TIMESTAMP, TIME_SLICE(TIMESTAMP, 5, 'MINUTE', 'START') AS WINDOW_START,
        ENGINE_TEMP, TRANS_OIL_PRESSURE, BATTERY_VOLTAGE
    FROM NEW_FTFP.DATA.TELEMETRY
),
aggregated_features AS (
    SELECT
        ENTITY_ID, WINDOW_START, MAX(TIMESTAMP) AS FEATURE_TIMESTAMP,
        AVG(ENGINE_TEMP) AS AVG_ENGINE_TEMP,
        AVG(TRANS_OIL_PRESSURE) AS AVG_TRANS_OIL_PRESSURE,
        AVG(BATTERY_VOLTAGE) AS AVG_BATTERY_VOLTAGE,
        STDDEV(BATTERY_VOLTAGE) AS STDDEV_BATTERY_VOLTAGE,
        STDDEV(ENGINE_TEMP) AS STDDEV_ENGINE_TEMP,
        STDDEV(TRANS_OIL_PRESSURE) AS STDDEV_TRANS_OIL_PRESSURE,
        COUNT(*) AS RECORD_COUNT
    FROM time_windows
    GROUP BY ENTITY_ID, WINDOW_START
),
slope_calculations AS (
    SELECT a.*,
        (a.AVG_ENGINE_TEMP - LAG(a.AVG_ENGINE_TEMP) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) / 5.0 AS SLOPE_ENGINE_TEMP,
        (a.AVG_TRANS_OIL_PRESSURE - LAG(a.AVG_TRANS_OIL_PRESSURE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) / 5.0 AS SLOPE_TRANS_OIL_PRESSURE,
        (a.AVG_BATTERY_VOLTAGE - LAG(a.AVG_BATTERY_VOLTAGE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) / 5.0 AS SLOPE_BATTERY_VOLTAGE,
        AVG(a.AVG_ENGINE_TEMP) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ROLLING_AVG_ENGINE_TEMP,
        AVG(a.AVG_TRANS_OIL_PRESSURE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ROLLING_AVG_TRANS_OIL_PRESSURE,
        SUM(a.STDDEV_BATTERY_VOLTAGE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_VOLATILITY,
        SUM(CASE WHEN a.STDDEV_BATTERY_VOLTAGE > 0.7 THEN 1 ELSE 0 END) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ELEVATED_WINDOW_COUNT,
        (a.STDDEV_BATTERY_VOLTAGE - LAG(a.STDDEV_BATTERY_VOLTAGE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) AS VOLATILITY_DELTA,
        (a.AVG_ENGINE_TEMP - LAG(a.AVG_ENGINE_TEMP) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) -
        (LAG(a.AVG_ENGINE_TEMP) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP) - LAG(a.AVG_ENGINE_TEMP, 2) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) AS TEMP_ACCELERATION,
        (a.AVG_TRANS_OIL_PRESSURE - LAG(a.AVG_TRANS_OIL_PRESSURE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) -
        (LAG(a.AVG_TRANS_OIL_PRESSURE) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP) - LAG(a.AVG_TRANS_OIL_PRESSURE, 2) OVER (PARTITION BY a.ENTITY_ID ORDER BY a.FEATURE_TIMESTAMP)) AS PRESSURE_ACCELERATION
    FROM aggregated_features a
)
SELECT
    ENTITY_ID, FEATURE_TIMESTAMP, AVG_ENGINE_TEMP, AVG_TRANS_OIL_PRESSURE, AVG_BATTERY_VOLTAGE,
    STDDEV_BATTERY_VOLTAGE, STDDEV_ENGINE_TEMP, STDDEV_TRANS_OIL_PRESSURE,
    COALESCE(SLOPE_ENGINE_TEMP, 0) AS SLOPE_ENGINE_TEMP,
    COALESCE(SLOPE_TRANS_OIL_PRESSURE, 0) AS SLOPE_TRANS_OIL_PRESSURE,
    COALESCE(SLOPE_BATTERY_VOLTAGE, 0) AS SLOPE_BATTERY_VOLTAGE,
    ROLLING_AVG_ENGINE_TEMP, ROLLING_AVG_TRANS_OIL_PRESSURE,
    COALESCE(CUMULATIVE_VOLATILITY, 0) AS CUMULATIVE_VOLATILITY,
    COALESCE(ELEVATED_WINDOW_COUNT, 0) AS ELEVATED_WINDOW_COUNT,
    COALESCE(VOLATILITY_DELTA, 0) AS VOLATILITY_DELTA,
    COALESCE(TEMP_ACCELERATION, 0) AS TEMP_ACCELERATION,
    COALESCE(PRESSURE_ACCELERATION, 0) AS PRESSURE_ACCELERATION
FROM slope_calculations
WHERE RECORD_COUNT >= 12;

-- ===========================================================================
-- View 3: ROUTE_GEOMETRY_DETAILED (backward compat, uses legacy FREIGHT_EDGES)
-- In NEW_FTFP, Valhalla generates route geometry dynamically
-- ===========================================================================

CREATE OR REPLACE VIEW ROUTE_GEOMETRY_DETAILED AS
WITH route_edges AS (
    SELECT
        trn.ENTITY_ID,
        trn.SEQUENCE_NUM,
        trn.NODE_ID as FROM_NODE,
        LEAD(trn.NODE_ID) OVER (PARTITION BY trn.ENTITY_ID ORDER BY trn.SEQUENCE_NUM) as TO_NODE
    FROM NEW_FTFP.DATA.TRUCK_ROUTE_NODES trn
),
route_with_geometry AS (
    SELECT
        re.ENTITY_ID,
        re.SEQUENCE_NUM,
        CASE
            WHEN fe.FROM_NODE = re.FROM_NODE
            THEN fe.ROAD_GEOMETRY_SAMPLED:coordinates
            ELSE ARRAY_REVERSE(fe.ROAD_GEOMETRY_SAMPLED:coordinates)
        END as segment_coords
    FROM route_edges re
    JOIN NEW_FTFP.DATA.FREIGHT_EDGES fe
        ON (fe.FROM_NODE = re.FROM_NODE AND fe.TO_NODE = re.TO_NODE)
        OR (fe.FROM_NODE = re.TO_NODE AND fe.TO_NODE = re.FROM_NODE)
    WHERE re.TO_NODE IS NOT NULL
),
flattened AS (
    SELECT
        ENTITY_ID,
        SEQUENCE_NUM,
        f.INDEX as coord_idx,
        f.VALUE as coord
    FROM route_with_geometry,
         LATERAL FLATTEN(input => segment_coords) f
),
route_coords AS (
    SELECT
        ENTITY_ID,
        ARRAY_AGG(coord) WITHIN GROUP (ORDER BY SEQUENCE_NUM, coord_idx) as coordinates
    FROM flattened
    GROUP BY ENTITY_ID
)
SELECT
    rc.ENTITY_ID,
    tr.ROUTE_NAME,
    tr.START_CITY,
    tr.END_CITY,
    OBJECT_CONSTRUCT('type', 'LineString', 'coordinates', rc.coordinates) AS GEOMETRY,
    ARRAY_SIZE(rc.coordinates) AS POINT_COUNT
FROM route_coords rc
JOIN NEW_FTFP.DATA.TRUCK_ROUTES tr ON rc.ENTITY_ID = tr.ENTITY_ID;

-- ===========================================================================
-- View 4: ENHANCED_PREDICTIVE_VIEW_HYBRID_TTF
-- ===========================================================================

CREATE OR REPLACE VIEW ENHANCED_PREDICTIVE_VIEW_HYBRID_TTF AS
WITH latest_features AS (
    SELECT
        FEATURE_TIMESTAMP AS PREDICTION_TIMESTAMP, ENTITY_ID,
        AVG_ENGINE_TEMP, AVG_TRANS_OIL_PRESSURE, AVG_BATTERY_VOLTAGE,
        STDDEV_BATTERY_VOLTAGE, STDDEV_ENGINE_TEMP, STDDEV_TRANS_OIL_PRESSURE,
        SLOPE_ENGINE_TEMP, SLOPE_TRANS_OIL_PRESSURE, SLOPE_BATTERY_VOLTAGE,
        ROLLING_AVG_ENGINE_TEMP, ROLLING_AVG_TRANS_OIL_PRESSURE,
        CUMULATIVE_VOLATILITY, ELEVATED_WINDOW_COUNT, VOLATILITY_DELTA,
        TEMP_ACCELERATION, PRESSURE_ACCELERATION,
        ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY FEATURE_TIMESTAMP DESC) AS rn
    FROM NEW_FTFP.DATA.FEATURE_ENGINEERING_VIEW_TEMPORAL
),
with_classification AS (
    SELECT *,
        NEW_FTFP.DATA.CLASSIFY_FAILURE_ML(
            AVG_ENGINE_TEMP, AVG_TRANS_OIL_PRESSURE, AVG_BATTERY_VOLTAGE,
            STDDEV_BATTERY_VOLTAGE, STDDEV_ENGINE_TEMP, STDDEV_TRANS_OIL_PRESSURE,
            SLOPE_ENGINE_TEMP, SLOPE_TRANS_OIL_PRESSURE, SLOPE_BATTERY_VOLTAGE,
            ROLLING_AVG_ENGINE_TEMP, ROLLING_AVG_TRANS_OIL_PRESSURE
        ) AS PREDICTED_FAILURE_TYPE
    FROM latest_features WHERE rn = 1
)
SELECT
    PREDICTION_TIMESTAMP, ENTITY_ID,
    AVG_ENGINE_TEMP AS CURRENT_ENGINE_TEMP,
    AVG_TRANS_OIL_PRESSURE AS CURRENT_TRANS_PRESSURE,
    AVG_BATTERY_VOLTAGE AS CURRENT_BATTERY_VOLTAGE,
    PREDICTED_FAILURE_TYPE,
    CASE
        WHEN PREDICTED_FAILURE_TYPE = 'ELECTRICAL_FAILURE'
        THEN NEW_FTFP.DATA.PREDICT_TTF_TEMPORAL(
            AVG_ENGINE_TEMP, AVG_TRANS_OIL_PRESSURE, AVG_BATTERY_VOLTAGE,
            STDDEV_BATTERY_VOLTAGE, STDDEV_ENGINE_TEMP, STDDEV_TRANS_OIL_PRESSURE,
            SLOPE_ENGINE_TEMP, SLOPE_TRANS_OIL_PRESSURE, SLOPE_BATTERY_VOLTAGE,
            ROLLING_AVG_ENGINE_TEMP, ROLLING_AVG_TRANS_OIL_PRESSURE,
            CUMULATIVE_VOLATILITY, ELEVATED_WINDOW_COUNT, VOLATILITY_DELTA,
            TEMP_ACCELERATION, PRESSURE_ACCELERATION
        )
        WHEN PREDICTED_FAILURE_TYPE IN ('ENGINE_FAILURE', 'TRANSMISSION_FAILURE')
        THEN NEW_FTFP.DATA.PREDICT_TTF_ML(
            AVG_ENGINE_TEMP, AVG_TRANS_OIL_PRESSURE, AVG_BATTERY_VOLTAGE,
            STDDEV_BATTERY_VOLTAGE, STDDEV_ENGINE_TEMP, STDDEV_TRANS_OIL_PRESSURE,
            SLOPE_ENGINE_TEMP, SLOPE_TRANS_OIL_PRESSURE, SLOPE_BATTERY_VOLTAGE,
            ROLLING_AVG_ENGINE_TEMP, ROLLING_AVG_TRANS_OIL_PRESSURE
        )
        ELSE NULL
    END AS PREDICTED_HOURS_TO_FAILURE,
    CASE
        WHEN PREDICTED_FAILURE_TYPE = 'ELECTRICAL_FAILURE' THEN 'temporal_16_features'
        WHEN PREDICTED_FAILURE_TYPE IN ('ENGINE_FAILURE', 'TRANSMISSION_FAILURE') THEN 'basic_11_features'
        ELSE 'none'
    END AS TTF_MODEL_USED
FROM with_classification;
