-- ============================================================================
-- FTFP Setup SQL - Database, Tables, and Stages
-- ============================================================================

CREATE DATABASE IF NOT EXISTS NEW_FTFP
COMMENT = 'Fleet Telemetry Failure Prediction';

CREATE SCHEMA IF NOT EXISTS NEW_FTFP.DATA
COMMENT = 'All FTFP tables, views, functions, and stages';

USE DATABASE NEW_FTFP;
USE SCHEMA DATA;

CREATE WAREHOUSE IF NOT EXISTS NEW_FTFP_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for FTFP operations';

CREATE STAGE IF NOT EXISTS NEW_FTFP.DATA.ML_MODELS
COMMENT = 'Internal stage for ML model files (.pkl.gz)';

CREATE STAGE IF NOT EXISTS NEW_FTFP.DATA.DATA_STAGE
COMMENT = 'Internal stage for seed data loading';

CREATE IMAGE REPOSITORY IF NOT EXISTS NEW_FTFP.DATA.FTFP_REPO
COMMENT = 'Container images for FTFP service';

CREATE COMPUTE POOL IF NOT EXISTS NEW_FTFP_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300
  COMMENT = 'Compute pool for FTFP';

-- ===========================================================================
-- Seed Data Tables
-- ===========================================================================

CREATE TABLE IF NOT EXISTS NORMAL_SEED (
    ENTITY_ID VARCHAR(100),
    EPOCH NUMBER(38,0),
    ENGINE_TEMP FLOAT,
    TRANS_OIL_PRESSURE FLOAT,
    BATTERY_VOLTAGE FLOAT
);

CREATE TABLE IF NOT EXISTS ENGINE_FAILURE_SEED (
    ENTITY_ID VARCHAR(100),
    EPOCH NUMBER(38,0),
    ENGINE_TEMP FLOAT,
    TRANS_OIL_PRESSURE FLOAT,
    BATTERY_VOLTAGE FLOAT
);

CREATE TABLE IF NOT EXISTS TRANSMISSION_FAILURE_SEED (
    ENTITY_ID VARCHAR(100),
    EPOCH NUMBER(38,0),
    ENGINE_TEMP FLOAT,
    TRANS_OIL_PRESSURE FLOAT,
    BATTERY_VOLTAGE FLOAT
);

CREATE TABLE IF NOT EXISTS ELECTRICAL_FAILURE_SEED (
    ENTITY_ID VARCHAR(100),
    EPOCH NUMBER(38,0),
    ENGINE_TEMP FLOAT,
    TRANS_OIL_PRESSURE FLOAT,
    BATTERY_VOLTAGE FLOAT
);

-- ===========================================================================
-- Route & Service Center Tables
-- ===========================================================================

CREATE TABLE IF NOT EXISTS TRUCK_ROUTES (
    ENTITY_ID VARCHAR(100),
    ROUTE_NAME VARCHAR(200),
    START_CITY VARCHAR(100),
    END_CITY VARCHAR(100),
    START_LAT FLOAT,
    START_LNG FLOAT,
    END_LAT FLOAT,
    END_LNG FLOAT,
    TOTAL_DISTANCE_MILES FLOAT,
    TOTAL_DURATION_HOURS FLOAT
);

CREATE TABLE IF NOT EXISTS ROUTE_WAYPOINTS (
    ENTITY_ID VARCHAR(100),
    SEQUENCE_NUM NUMBER(38,0),
    LAT FLOAT,
    LNG FLOAT,
    CUMULATIVE_DISTANCE FLOAT
);

CREATE TABLE IF NOT EXISTS SERVICE_CENTERS (
    CENTER_ID NUMBER(38,0),
    CENTER_NAME VARCHAR(200),
    LAT FLOAT,
    LNG FLOAT,
    CENTER_TYPE VARCHAR(50),
    SPECIALTIES VARCHAR(500),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(10),
    HOURS VARCHAR(100),
    RATING FLOAT,
    CAPACITY NUMBER(38,0)
);

CREATE TABLE IF NOT EXISTS SERVICE_CENTER_ROUTES (
    ENTITY_ID VARCHAR(100),
    CENTER_ID NUMBER(38,0),
    DETOUR_DISTANCE_MILES FLOAT,
    DETOUR_DURATION_HOURS FLOAT,
    ORIGINAL_REMAINING_MILES FLOAT,
    DETOUR_OVERHEAD_MILES FLOAT
);

-- ===========================================================================
-- Graph Tables (legacy, used for route geometry visualization)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS FREIGHT_NODES (
    NODE_ID VARCHAR(100),
    NODE_NAME VARCHAR(200),
    LAT FLOAT,
    LNG FLOAT,
    NODE_TYPE VARCHAR(50),
    STATE VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS FREIGHT_EDGES (
    FROM_NODE VARCHAR(100),
    TO_NODE VARCHAR(100),
    DISTANCE_MILES FLOAT,
    DURATION_HOURS FLOAT,
    ROAD_TYPE VARCHAR(50),
    ROAD_GEOMETRY_SAMPLED VARIANT
);

CREATE TABLE IF NOT EXISTS TRUCK_ROUTE_NODES (
    ENTITY_ID VARCHAR(100),
    SEQUENCE_NUM NUMBER(38,0),
    NODE_ID VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ADJACENCY_LIST (
    NODE_ID VARCHAR(100),
    NEIGHBOR_ID VARCHAR(100),
    DISTANCE FLOAT
);

-- ===========================================================================
-- Detour Routes (pre-computed)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS DETOUR_ROUTES (
    ENTITY_ID VARCHAR(100),
    CENTER_ID NUMBER(38,0),
    CENTER_NAME VARCHAR(200),
    SEQUENCE_NUM NUMBER(38,0),
    LAT FLOAT,
    LNG FLOAT,
    CUMULATIVE_DISTANCE FLOAT
);

-- ===========================================================================
-- ML Training Table (used by ML_PIPELINE_BUILD_DEPLOY notebook)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS TRAINING_TBL (
    TIMESTAMP TIMESTAMP_NTZ(9),
    ENTITY_ID VARCHAR(100),
    FAILURE_TYPE VARCHAR(50),
    TIME_TO_FAILURE FLOAT,
    ENGINE_TEMP FLOAT,
    TRANS_OIL_PRESSURE FLOAT,
    BATTERY_VOLTAGE FLOAT,
    FAILURE_FLAG NUMBER(38,0)
);

-- ===========================================================================
-- Runtime Tables (populated during simulation)
-- ===========================================================================

CREATE OR REPLACE TABLE TELEMETRY CLUSTER BY (TIMESTAMP)(
    TIMESTAMP TIMESTAMP_NTZ(9),
    ENTITY_ID VARCHAR(100),
    ENGINE_TEMP FLOAT,
    TRANS_OIL_PRESSURE FLOAT,
    BATTERY_VOLTAGE FLOAT,
    STATUS VARCHAR(20) DEFAULT 'NORMAL'
);

CREATE OR REPLACE TABLE STREAM_STATE (
    STREAM_NAME VARCHAR(100) NOT NULL,
    START_TS TIMESTAMP_NTZ(9),
    NEXT_EPOCH NUMBER(38,0),
    STEP_SECONDS NUMBER(38,0),
    LAST_UPDATED TIMESTAMP_NTZ(9),
    PRIMARY KEY (STREAM_NAME)
);

INSERT INTO STREAM_STATE (STREAM_NAME, START_TS, NEXT_EPOCH, STEP_SECONDS, LAST_UPDATED)
VALUES ('NORMAL_TO_TELEMETRY', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ, 0, 5, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ);

CREATE OR REPLACE TABLE PREDICTION_CACHE (
    ENTITY_ID VARCHAR(100) NOT NULL,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
    PREDICTED_FAILURE_TYPE VARCHAR(50),
    PREDICTED_HOURS_TO_FAILURE FLOAT,
    TTF_MODEL_USED VARCHAR(50),
    CURRENT_ENGINE_TEMP FLOAT,
    CURRENT_TRANS_PRESSURE FLOAT,
    CURRENT_BATTERY_VOLTAGE FLOAT,
    LAST_UPDATED TIMESTAMP_NTZ(9),
    PRIMARY KEY (ENTITY_ID)
);

CREATE OR REPLACE TABLE ACTIVE_FAILURES (
    ENTITY_ID VARCHAR(100) NOT NULL,
    FAILURE_TYPE VARCHAR(50),
    STARTED_AT TIMESTAMP_NTZ(9),
    EPOCH_STARTED NUMBER(38,0),
    LAST_UPDATED TIMESTAMP_NTZ(9),
    PRIMARY KEY (ENTITY_ID)
);

CREATE OR REPLACE TABLE FAILURE_CONFIG (
    ENTITY_ID VARCHAR(100) NOT NULL,
    FAILURE_TYPE VARCHAR(50),
    ENABLED BOOLEAN,
    EFFECTIVE_FROM_EPOCH NUMBER(38,0),
    FAILURE_NEXT_EPOCH NUMBER(38,0),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (ENTITY_ID)
);

CREATE OR REPLACE TABLE FIRST_FAILURE_MARKERS (
    ENTITY_ID VARCHAR(100) NOT NULL,
    FIRST_FAILURE_TIME TIMESTAMP_NTZ(9),
    FAILURE_TYPE VARCHAR(50),
    LAST_UPDATED TIMESTAMP_NTZ(9),
    BREAKDOWN_EPOCH NUMBER(38,0),
    PRIMARY KEY (ENTITY_ID)
);

CREATE OR REPLACE TABLE VALHALLA_ROUTE_CACHE (
    CACHE_KEY VARCHAR(500) NOT NULL,
    ORIGIN_LAT FLOAT,
    ORIGIN_LNG FLOAT,
    DEST_LAT FLOAT,
    DEST_LNG FLOAT,
    COSTING VARCHAR(20) DEFAULT 'truck',
    DISTANCE_MILES FLOAT,
    DURATION_HOURS FLOAT,
    GEOMETRY VARIANT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CACHE_KEY)
);

CREATE OR REPLACE TABLE SERVICE_CENTER_ROAD_DISTANCES (
    FROM_TYPE VARCHAR(20),
    FROM_ID VARCHAR(100),
    FROM_LAT FLOAT,
    FROM_LNG FLOAT,
    TO_CENTER_ID NUMBER(38,0),
    TO_LAT FLOAT,
    TO_LNG FLOAT,
    ROAD_DISTANCE_MILES FLOAT,
    ROAD_DURATION_HOURS FLOAT,
    COMPUTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (FROM_ID, TO_CENTER_ID)
);
